### PR TITLE
Implementing functions for scripts

### PR DESCRIPTION
**Pull request by elmigranto**

### CODE REVIEW

**Comment by elmigranto** [comment]
I didn't do anything about managing parallel requests. Node used to have a configurable limit on number of connections to the same host, but it seems it is gone by default now (see [`http.Agent`](https://nodejs.org/dist/latest-v6.x/docs/api/http.html#http_class_http_agent)). So we are effectively bombarding server with a bunch of HTTP requests as fast as we can. There might be some issues with rate-limiting, running out of sockets (theoretically :), or something similar. Also, we might benefit from enabling `keep-alive`, or adding batch processing to the server itself.

Anything we want to do about this at the moment?

Also, would be nice to have some actual data for testing game analyzer script…

**Comment by j3k0** [comment]
Well, I'd rather not use parallel requests for those scripts, but sequential ones. It's better that it do not add a lot of pressure on the server, and it's fine if it requires a few minutes to run.

**Comment by j3k0** [comment]
Concerning actual data, I'll deploy the updated services to prod and will give you URL and API_SECRET. For now (at least) turngame image failed to build on Dockerhub, so I have to check out why.

**Comment by j3k0** [comment]
Added sample data to the repo.

You can probably static serve the "sample-data" folder, that should behave like the server would.

It might be even better to allow the script to be run on a static folder like this one? The `snapshot.sh` can be used to fetch data. (last commit)

JC

**Comment by elmigranto** [comment]
I see some inconsistencies in the data, and not sure whether that how things are, or something is simply missing from test files.
1. `active` games — are those "cross-referenced", for example, if `alice` is playing `bob` in the game with id `deadbeef`, will they both have a game with that ID inside `coordinator/active-games`? Or do I query both ends?
   
   Same is true for game info from `turngame` and `statistics` — often only one of the participants have stats on particular game ID.
2. Some games have `endTime` 0. I guess we compare `startTime` then? Or do we sort by `endTime` first, check whether there are multiple candidates, and then comparet `startTime`s on those?

**Comment by elmigranto** [comment]
Regarding №1 — I reread specs for relevant modules, seems the problem in samples themselves and querying any user should result in same data. I'm implementing based off samples anyways, though.

**Comment by elmigranto** [comment]
Statistics and Coordinator module use `/:gametype/:version/…` endpoints, I assume it is safe to use `triominos` as `gametype` and `v1` as a `version`?

**Comment by elmigranto** [comment]
I've added game fetching for priorities 1–3. Current `./analyze-games` script takes 2 usernames and fetches a game that will be analyzed. You can try this on actual data:

``` bash
export API_SECRET=42
export PROTO=https
export HOST=prod.ggs.ovh
export PORT=443

./analyze-games alice bob
```

**Comment by elmigranto** [comment]
Is it possible to have same score on finished game (`gameover` in Coordinator, or `gameover` in archive)?

**Comment by j3k0** [comment]
> seems the problem in samples themselves

Could be, since I didn't want to publish real players data, I may have messed them up when renaming real player names to more anonymous ones...

**Comment by elmigranto** [comment]
Okay. I've added invitations in, should be complete, except couple of untestable things on samples:
- [ ] fix start/end dates:
  - [ ] start/end in coordinator (sample data is all zeroes, sample `output.txt` is a bit strange too containing `1` instead of `endDate`) — should be fine, if underlying values are fine;
  - [ ] in archive there is a single `date` property, not sure what that is (treating it as `start` for now), not sure where to get the other one (probably nowhere?);
  - [x] I see that everything in database is in seconds, so I multiply by 1000 and convert to UTC string.
- [ ] invitations:
  - [ ] invitations have no dates, no way to know who send first, so it is simple `if/else` that takes first username (`user0` or `userX`) as a winner, if multiple back-forth invites are found (probably not a problem);
  - [ ] there is no status on invitations, I assume that if it's there it's active and multiples aren't allowed;
- [ ] remove extraneous requests (mentioned earlier about fetching stuff for both players).

**Comment by elmigranto** [comment]
@j3k0 the `./analyze-games` script should work now as described in README, I'd appreciate if you try it out on real data. I outlined some issues above that may arise, but I don't really have a way to check.

Script also dumps some stuff in `stderr` (what it downloads per username pair).

**Comment by j3k0** [comment]
@elmigranto Feel free to merge #2.

Tested using the following `input.txt`:

```
jeko jeko2
jeko jeko3
```

It fails with the following output:

```
fetchGame() jeko jeko2
  trying finished-coordinator-game…
  trying archived-game…
fetchGame() jeko jeko3
  trying finished-coordinator-game…
  trying archived-game…
  trying in-progress-coordinator-game…
  trying invitation…
  trying nothing-found…
Usage:

  analyze-games input [parallelism]

    * input — path to the file
    * parallelism (defaults to 1) — process this number of inputs at a time

TypeError: Cannot read property '__analyze_kind' of null
    at e (/Users/jeko/Documents/triominos/ganomede/ganomede-analyze-games/bin/analyze-games:20:26)
    at async.whilst (/Users/jeko/Documents/triominos/ganomede/ganomede-analyze-games/src/utils.js:65:16)
    at /Users/jeko/Documents/triominos/ganomede/ganomede-analyze-games/node_modules/async/dist/async.js:847:20
    at /Users/jeko/Documents/triominos/ganomede/ganomede-analyze-games/node_modules/async/dist/async.js:4909:22
    at /Users/jeko/Documents/triominos/ganomede/ganomede-analyze-games/node_modules/async/dist/async.js:339:31
    at fn (/Users/jeko/Documents/triominos/ganomede/ganomede-analyze-games/src/utils.js:58:9)
    at fn (/Users/jeko/Documents/triominos/ganomede/ganomede-analyze-games/src/fetch.js:117:7)
    at wrap (/Users/jeko/Documents/triominos/ganomede/ganomede-analyze-games/src/fetch.js:126:49)
    at /Users/jeko/Documents/triominos/ganomede/ganomede-analyze-games/src/fetch.js:110:5
    at callFn (/Users/jeko/Documents/triominos/ganomede/ganomede-analyze-games/src/utils.js:53:7)
```

**Comment by j3k0** [comment]
@elmigranto BTW, for faster testing, PR #3 allows you to run experiments from local files:

```
PROTO=file DIR=`pwd`/my-snapshot API_SECRET=secret ./analyze-games test-snapshot/input.txt
```

**Comment by elmigranto** [comment]
Fixed a `null` bug, running against prod server (as well as output of new `snapshot.sh`) seems fine, however most searches end up in either `archive` or `nothing-found` (probably as expected, though).

I never saw an `active` or `gameover` game from coordinator, so that is only tested by original `./sample-data` and has `endDate` problem "unresolved".

**Comment by j3k0** [comment]
Added an invitation between `jeko2` and `jeko9`. It seems to work (on this single test case).

**Comment by j3k0** [comment]
Hey Alexey, there's a small change to the requirements, hope it's not gonna be too much trouble.

If environment variable `TOURNAMENT_START` is defined...

If `new Date(process.env.TOURNAMENT_START)` is not valid, exit with error. Else...

If there's 1 or more games in the archive that is newer than this date, then...

The first of the archived games among those that are newer than this date is to be chosen with the highest priority.

If not, proceed as before (active gameover, last archived game, etc.)

**Comment by elmigranto** [comment]
If `TOURNAMENT_START` is set and valid, but there are no archived games since `TOURNAMENT_START`, we use `gameover -> last archived -> active…`, correct?

**Comment by elmigranto** [comment]
> The first of the archived games

Let's say 3 games are played since the date, we chose the first one, not latest, right?

**Comment by elmigranto** [comment]
Added `TOURNAMENT_START` with assumptions above, `last` part is easy to change, but if I'm wrong about [priorities](https://github.com/j3k0/ganomede-analyze-games/pull/2#issuecomment-251671118), let me know!

``` bash
# elmigranto @ prod in ~/Work/j3k0/ganomede-analyze-games on git:implmentation x [18:28:21] 
$ TOURNAMENT_START=1 ./analyze-games --one jeko jeko2 
Running with TOURNAMENT_START (1) Thu Jan 01 1970 05:00:00 GMT+0500 (SVET)
fetchGame() jeko jeko2
  trying tournament-archive-game…
username0,username1,started,ended,winner,score0,score1
jeko,jeko2,2016-01-24T14:13:58.101Z,,jeko2,105,108 # first game since timestamp 1

# elmigranto @ prod in ~/Work/j3k0/ganomede-analyze-games on git:implmentation x [18:28:42] 
$ TOURNAMENT_START=1475674133381 ./analyze-games --one jeko jeko2
Running with TOURNAMENT_START (1475674133381) Wed Oct 05 2016 18:28:53 GMT+0500 (YEKT)
fetchGame() jeko jeko2
  trying tournament-archive-game…
  trying finished-coordinator-game…
  trying archived-game…
username0,username1,started,ended,winner,score0,score1
jeko,jeko2,2016-04-08T14:20:12.680Z,,jeko,-58,-220 # most recent game from `archive`
```

**Comment by elmigranto** [comment]
Maybe we should add printing object it analyzes to `stderr`, should make easier to verify.

**Comment by j3k0** [comment]
> If TOURNAMENT_START is set and valid, but there are no archived games since TOURNAMENT_START, we use gameover -> last archived -> active, correct?

Correct

> Let's say 3 games are played since the date, we chose the first one, not latest, right?

Yup

**Comment by j3k0** [comment]
I realize I didn't answer this:

> Some games have endTime 0. I guess we compare startTime then?

Yes. The client doesn't allow to games to run in parallel between the same players, so comparing `startDate` is enough.

I guess we're all done with those scripts now, right?

Since we can now "snapshot" the database (kind-of) using the `snapshot.sh` script, if there's any issue we run into when analyzing the tournaments' first round, we can come back and fix the code. Re-run on "snapshoted" data.

Did I missed anything that is left?

**Comment by elmigranto** [comment]
Yep, everything should be in place, and with snapshotting we can be sure nothing goes too awry. Though, some stuff can disappear or chage inside DB (like invitations or game status). Shouldn't be a problem with game status (since it goes to archive), but rejecting invites may result in `nothing-found` situation.

The only thing left is that when fetching coordinator games it does 2 requests, 1 for each player. This was because test data wasn't "symmetrical" (player0 had an active game with player1, but player1's data didn't reflected that). That part is still in (it filters unique games and makes sure replies are the same, though), but let me know if we want to ditcth that, or make it togglable.

**Comment by j3k0** [comment]
> when fetching coordinator games it does 2 requests, 1 for each player

It doesn't matter at all if we waste some requests or if it's not 100% clean, as long as the result is right. So let's keep it like that.

**Pull request merged**
